language: python
python:
  - '3.6'
before_script:
  - pip install git+https://github.com/divyanshuchauhan/aristotle-metadata-registry.git
  - pip install -r ./test_project/requirements.txt
  - pip install django-filter==1.1.0
  - ./test_project/manage.py migrate
  - ./test_project/manage.py collectstatic
  - ./test_project/manage.py createcachetable
  - ./test_project/manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin@myproject.com', 'password')"
  - ./test_project/manage.py create_access_token
  - nohup ./test_project/manage.py runserver &

script:
  - python -m unittest tests.utils_unittest
  - python -m unittest tests.integrationtest
