language: python
python:
  - '3.6'
before_script:
  - pip install coveralls
  - pip install git+https://github.com/divyanshuchauhan/aristotle-metadata-registry.git@api_fixes
  - pip install -r ./test_project/requirements.txt
  - pip install django-filter==1.1.0
  - ./test_project/manage.py migrate
  - ./test_project/manage.py collectstatic
  - ./test_project/manage.py createcachetable
  - ./test_project/manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin@myproject.com', 'password')"
  - nohup ./test_project/manage.py runserver 0.0.0.0:8080 &
  - sleep 15

script:
  - ./test_project/manage.py create_access_token
  - output=`./test_project/manage.py create_access_token|tail -n 1`
  - echo $output
  - coverage run --source=demo_meta_miner -m unittest discover -s tests -p '*test.py'

after_success:
  - coveralls

